// Backend resource catalogue. Each row maps to a real Django REST endpoint in
// github.com/MythicalCosmic/starforge_edu/config/urls.py. The generic staff
// workspace renders only entries granted by the signed-in profile.

export const STAFF_RESOURCES = [
  {
    id: 'students',
    endpoint: 'students/',
    permission: 'students',
    path: '/students',
    nav: 'students',
    icon: 'users',
    group: 'people',
    title: 'Students',
    singular: 'student',
  },
  {
    id: 'staff',
    endpoint: 'users/',
    permission: 'users',
    path: '/staff',
    nav: 'staff',
    icon: 'user',
    group: 'people',
    title: 'Staff directory',
    singular: 'staff member',
    readOnly: true,
  },
  {
    id: 'teachers',
    endpoint: 'teachers/',
    permission: 'teachers',
    path: '/teachers',
    nav: 'teachers',
    icon: 'user',
    group: 'people',
    title: 'Teachers',
    singular: 'teacher',
  },
  {
    id: 'parents',
    endpoint: 'parents/',
    permission: 'parents',
    path: '/parents',
    nav: 'parents',
    icon: 'users',
    group: 'people',
    title: 'Parents',
    singular: 'parent',
  },
  {
    id: 'cohorts',
    endpoint: 'cohorts/',
    permission: 'cohorts',
    path: '/cohorts',
    nav: 'cohorts',
    icon: 'cohort',
    group: 'learning',
    title: 'Groups',
    singular: 'group',
  },
  {
    id: 'schedule',
    endpoint: 'schedule/',
    permission: 'schedule',
    path: '/schedule',
    nav: 'schedule',
    icon: 'cal',
    group: 'learning',
    title: 'Schedule',
    singular: 'schedule item',
  },
  {
    id: 'attendance',
    endpoint: 'attendance/',
    permission: 'attendance',
    path: '/attendance',
    nav: 'attendance',
    icon: 'check',
    group: 'learning',
    title: 'Attendance',
    singular: 'attendance record',
  },
  {
    id: 'academics',
    endpoint: 'academics/',
    permission: 'academics',
    path: '/academics',
    nav: 'academics',
    icon: 'book',
    group: 'learning',
    title: 'Academics',
    singular: 'academic item',
  },
  {
    id: 'assignments',
    endpoint: 'assignments/',
    permission: 'assignments',
    path: '/assignments',
    nav: 'assignments',
    icon: 'doc',
    group: 'learning',
    title: 'Assignments',
    singular: 'assignment',
  },
  {
    id: 'content',
    endpoint: 'content/',
    permission: 'content',
    path: '/content',
    nav: 'content',
    icon: 'folder',
    group: 'learning',
    title: 'Content library',
    singular: 'content item',
  },
  {
    id: 'finance',
    endpoint: 'finance/',
    permission: 'finance',
    path: '/finance',
    nav: 'finance',
    icon: 'pie',
    group: 'operations',
    title: 'Finance',
    singular: 'finance record',
  },
  {
    id: 'payments',
    endpoint: 'payments/',
    permission: 'payments',
    path: '/payments',
    nav: 'payments',
    icon: 'brand',
    group: 'operations',
    title: 'Payments',
    singular: 'payment',
  },
  {
    id: 'printing',
    endpoint: 'printing/',
    permission: 'printing',
    path: '/printing',
    nav: 'printing',
    icon: 'print',
    group: 'operations',
    title: 'Printing',
    singular: 'print item',
  },
  {
    id: 'notifications',
    endpoint: 'notifications/',
    permission: 'notifications',
    path: '/notifications',
    nav: 'notifications',
    icon: 'bell',
    group: 'operations',
    title: 'Notifications',
    singular: 'notification',
  },
  {
    id: 'ai',
    endpoint: 'ai/',
    permission: 'ai_app',
    path: '/ai',
    nav: 'ai',
    icon: 'ai',
    group: 'operations',
    title: 'AI requests',
    singular: 'AI request',
  },
  {
    id: 'reports',
    endpoint: 'reports/',
    permission: 'reports',
    path: '/reports',
    nav: 'reports',
    icon: 'doc',
    group: 'operations',
    title: 'Reports',
    singular: 'report',
  },
  {
    id: 'audit',
    endpoint: 'audit/',
    permission: 'audit',
    path: '/audit',
    nav: 'audit',
    icon: 'shield',
    group: 'operations',
    title: 'Audit trail',
    singular: 'audit entry',
    readOnly: true,
  },
  {
    id: 'branches',
    endpoint: 'org/branches/',
    permission: 'org',
    path: '/organization/branches',
    nav: 'organization',
    icon: 'globe',
    group: 'operations',
    title: 'Branches',
    singular: 'branch',
    fields: ['name', 'slug', 'address', 'phone', 'timezone', 'is_active'],
  },
  {
    id: 'departments',
    endpoint: 'org/departments/',
    permission: 'org',
    path: '/organization/departments',
    nav: 'organization',
    icon: 'globe',
    group: 'operations',
    title: 'Departments',
    singular: 'department',
    fields: ['branch', 'name', 'slug', 'description', 'is_active'],
  },
];

export const STAFF_RESOURCE_BY_ID = Object.fromEntries(
  STAFF_RESOURCES.map((resource) => [resource.id, resource]),
);

export function staffResourceForPath(pathname) {
  const normalized = String(pathname ?? '').replace(/\/+$/, '') || '/';
  return [...STAFF_RESOURCES]
    .sort((a, b) => b.path.length - a.path.length)
    .find((resource) => normalized === resource.path || normalized.startsWith(`${resource.path}/`));
}
