import {
  LocalAccountRepository,
  LocalCohortRepository,
  LocalCardRepository,
  LocalTaskRepository,
  LocalDashboardRepository,
  LocalAiRepository,
  LocalPrintRepository,
  LocalSurveyRepository,
  LocalMgmtRepository,
  LocalNotificationRepository,
  LocalMaterialRepository,
  LocalNavigationRepository,
  LocalWorkRepository,
  LocalFinanceRepository,
  LocalPeopleRepository,
  LocalAcademicRepository,
  LocalOperationsRepository,
} from '@/data/repositories/local/index.js';
import { createServices } from '@/services/createServices.js';

export const services = createServices({
  accountRepo: new LocalAccountRepository(),
  cohortRepo: new LocalCohortRepository(),
  cardRepo: new LocalCardRepository(),
  taskRepo: new LocalTaskRepository(),
  dashboardRepo: new LocalDashboardRepository(),
  aiRepo: new LocalAiRepository(),
  printRepo: new LocalPrintRepository(),
  surveyRepo: new LocalSurveyRepository(),
  mgmtRepo: new LocalMgmtRepository(),
  notificationRepo: new LocalNotificationRepository(),
  materialRepo: new LocalMaterialRepository(),
  workRepo: new LocalWorkRepository(),
  financeRepo: new LocalFinanceRepository(),
  peopleRepo: new LocalPeopleRepository(),
  academicRepo: new LocalAcademicRepository(),
  operationsRepo: new LocalOperationsRepository(),
  navRepo: new LocalNavigationRepository(),
});
