import {
  MockAccountRepository,
  MockCohortRepository,
  MockCardRepository,
  MockTaskRepository,
  MockDashboardRepository,
  MockAiRepository,
  MockPrintRepository,
  MockSurveyRepository,
  MockMgmtRepository,
  MockNotificationRepository,
  MockMaterialRepository,
  MockWorkRepository,
  MockFinanceRepository,
  MockPeopleRepository,
  MockAcademicRepository,
  MockOperationsRepository,
} from '@/data/repositories/mock/index.js';
import { createServices } from '@/services/createServices.js';

export const services = createServices({
  accountRepo: new MockAccountRepository(),
  cohortRepo: new MockCohortRepository(),
  cardRepo: new MockCardRepository(),
  taskRepo: new MockTaskRepository(),
  dashboardRepo: new MockDashboardRepository(),
  aiRepo: new MockAiRepository(),
  printRepo: new MockPrintRepository(),
  surveyRepo: new MockSurveyRepository(),
  mgmtRepo: new MockMgmtRepository(),
  notificationRepo: new MockNotificationRepository(),
  materialRepo: new MockMaterialRepository(),
  workRepo: new MockWorkRepository(),
  financeRepo: new MockFinanceRepository(),
  peopleRepo: new MockPeopleRepository(),
  academicRepo: new MockAcademicRepository(),
  operationsRepo: new MockOperationsRepository(),
  navRepo: null,
});
