import {
  HttpAccountRepository,
  HttpCohortRepository,
  HttpCardRepository,
  HttpTaskRepository,
  LegacyHttpDashboardRepository,
  HttpAiRepository,
  HttpPrintRepository,
  HttpSurveyRepository,
  HttpMgmtRepository,
  HttpNotificationRepository,
  HttpMaterialRepository,
  HttpNavigationRepository,
  HttpWorkRepository,
  HttpFinanceRepository,
  HttpPeopleRepository,
  HttpAcademicRepository,
  HttpOperationsRepository,
} from '@/data/repositories/http/index.js';
import { createServices } from '@/services/createServices.js';

export const services = createServices({
  accountRepo: new HttpAccountRepository(),
  cohortRepo: new HttpCohortRepository(),
  cardRepo: new HttpCardRepository(),
  taskRepo: new HttpTaskRepository(),
  dashboardRepo: new LegacyHttpDashboardRepository(),
  aiRepo: new HttpAiRepository(),
  printRepo: new HttpPrintRepository(),
  surveyRepo: new HttpSurveyRepository(),
  mgmtRepo: new HttpMgmtRepository(),
  notificationRepo: new HttpNotificationRepository(),
  materialRepo: new HttpMaterialRepository(),
  workRepo: new HttpWorkRepository(),
  financeRepo: new HttpFinanceRepository(),
  peopleRepo: new HttpPeopleRepository(),
  academicRepo: new HttpAcademicRepository(),
  operationsRepo: new HttpOperationsRepository(),
  navRepo: new HttpNavigationRepository(),
});
